# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

pool:
  vmImage: 'Ubuntu-latest'

resources:
- repo: self

variables:
  nginx: 'old_nginx_dev'
  frontend: 'old_frontend_dev'
  backend: 'old_backend_dev'

stages:
- stage: Build
  displayName: Build, test and push images
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - script: docker build -t newecopeoplev1/$(frontend) ./frontend
    - script: docker build -t newecopeoplev1/$(backend) -f ./backend/Dockerfile.staging ./backend
    - script: docker build -t newecopeoplev1/$(nginx) ./nginx
  - job: test
    displayName: Test images
  - job: push
    displayName: Push image to docker hub
    steps:
    - script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - script: docker push newecopeoplev1/$(frontend)
    - script: docker push newecopeoplev1/$(backend)
    - script: docker push newecopeoplev1/$(nginx)

# heello