version: "3.4"

services:

  nginx:
    restart: always
    image: newecopeoplev1/old_nginx_dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/docker/letsencrypt-docker-nginx/src/production/production.conf:/etc/nginx/conf.d/default.conf
      - ~/docker/letsencrypt-docker-nginx/src/production/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ~/docker-volumes/etc/letsencrypt/live/newecopeople.com/fullchain.pem:/etc/letsencrypt/live/ohhaithere.com/fullchain.pem
      - ~/docker-volumes/etc/letsencrypt/live/newecopeople.com/privkey.pem:/etc/letsencrypt/live/ohhaithere.com/privkey.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt

  backend:
    image: newecopeoplev1/old_backend_dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultConnection=${POSTGRES_CONNECTION_STRING}
    ports:
      - "5000"
  
  frontend:
    image: newecopeoplev1/old_frontend_dev
    ports:
      - "4200"
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --staging -d example.com  -d www.example.com
  