version: "3.4"

services:

  nginx:
    restart: always
    image: newecopeoplev1/old_nginx_dev:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker/letsencrypt-docker-nginx/src/production/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/newecopeople.com/fullchain.pem:/etc/letsencrypt/live/newecopeople.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/newecopeople.com/privkey.pem:/etc/letsencrypt/live/newecopeople.com/privkey.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt

  backend:
    image: newecopeoplev1/old_backend_dev:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultConnection=${POSTGRES_CONNECTION_STRING}
    ports:
      - "5000"
  
  frontend:
    image: newecopeoplev1/old_frontend_dev:latest
    ports:
      - "4200"

  webhook:
    restart: unless-stopped
    image: staticfloat/docker-webhook
    volumes:
        # Mount this code into /code
        - ./:/code
        # Mount the docker socket
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        - WEBHOOK_SECRET=${WEBHOOK_SECRET}
        - WEBHOOK_HOOKS_DIR=/code/hooks
        - WEBHOOK_BRANCH_LIST=develop
    expose:
        - 8000