version: "3.4"

services:

  backend:
    image: newecopeoplev1/old_backend_dev:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection
      - SENDGRID_APIKEY
      - CLOUDINARY_DETAILS
    ports:
      - "5000:5000"
  
  frontend:
    image: newecopeoplev1/old_frontend_dev:latest
    ports:
      - "4200:4200"
